### PR TITLE
feat: add rwaERC20-bridge-example

### PR DESCRIPTION
**Pull request by pyk**
This pull request add `rwaERC20-bridge-example`.

[`CustomERC20Wrapped`](./contracts/mocks/CustomERC20Wrapped.sol) have `BLACKLISTER_ROLE` which can blacklist any account to:
- Receive token from L1
- Send or receive token in L2
- Bridge back token from L2 to L1

### CODE REVIEW

**Comment by invocamanman** [comment]
Hey! i thank you so much for your contributions eheh ^^
if you sign the CLA i will merge your PR
Also i rename `lib` to `Base` which i think seems better https://github.com/0xPolygonHermez/code-examples/commit/c6309070aa0b388fe4998de67f5dcaba7f31d8d1

If you want you can do it also ^^
Thank you! ^^

**Comment by pyk** [comment]
@invocamanman is this correct way to sign the CLA? https://github.com/0xPolygonHermez/clabot-config/pull/53

> Also i rename lib to Base which i think seems better https://github.com/0xPolygonHermez/code-examples/commit/c6309070aa0b388fe4998de67f5dcaba7f31d8d1

Ok let me update the contract name

**Comment by invocamanman** [comment]
I do think so, let me contact the person that's in charge of the CLA before merging it.
And thank you so much :D

**Review by invocamanman — APPROVED** [review]

**Comment by invocamanman** [comment]
merged ^^

**Comment by pyk** [comment]
thank you so much @invocamanman 🙇

**Pull request merged**
